export const ADD_FLARE_SCORE = 'ADD_FLARE_SCORE';
export const SET_TOKEN_FLARE_SCORE = 'SET_TOKEN_FLARE_SCORE';
export const SET_TOKEN_MEGA_SCORE = 'SET_TOKEN_MEGA_SCORE';
export const ADD_SPIN = 'ADD_SPIN';
export const ADD_MEGA_SPIN = 'ADD_MEGA_SPIN';
export const ADD_NIKE_SPIN = 'ADD_NIKE_SPIN';